language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

matrix:
  include:
  - r: release
    env: rlang='CRAN'
    before_install:
    - mkdir ~/.R
    - cp Makevars ~/.R
    - nvm install stable
    - npm install netlify-cli -g
    deploy:
      provider: script
      script: netlify deploy --prod --dir _book
      skip_cleanup: true
  - r: release
    env: rlang='github'
    before_install: Rscript -e "remotes::install_github('r-lib/rlang')"
