language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 1.17.2

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g
- git clone --recursive https://github.com/hadley/emo.git
- R -e 'devtools::install("emo")'

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- netlify deploy -t $NETLIFY_PAT
