language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_script:
- mkdir ~/.R
- cp Makevars ~/.R
script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

env:
  - NETLIFY_SITE_ID=5f44615c-61a2-4481-80ca-dcfa21e31f4b
  # NETLIFY_AUTH_TOKEN set in travis settings

matrix:
  include:
  - r: release
    env: rlang='CRAN'
    after_success:
    - nvm install stable
    - npm install netlify-cli -g
    deploy:
      provider: script
      script: netlify deploy --prod --dir _book
      skip_cleanup: true
  - r: release
    env: rlang='github'
    before_script: Rscript -e "remotes::install_github('r-lib/rlang')"
