language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_script:
- mkdir ~/.R
- cp Makevars ~/.R
script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

matrix:
  include:
  - r: release
    env: rlang='CRAN'
    after_success:
    - nvm install stable
    - npm install netlify-cli -g
    - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
    - echo $COMMIT_MSG
    - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
    - echo $DEPLOY_MSG
    deploy:
      provider: script
      script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
      skip_cleanup: true
  - r: release
    env: rlang='github'
    before_script: Rscript -e "remotes::install_github('r-lib/rlang')"
