language:r
sudo: false
cache: packages

before_install:
  - travis_retry gem install jekyll mime-types
  - mkdir ~/.R
  - cp Makevars ~/.R

script: jekyll build

after_success:
  - cp -r figures/ _site/figures

deploy:
  provider: s3
  access_key_id: AKIAJYY6UT5EHUXEKWCA
  secret_access_key:
    secure: "Ogjfu+wBbKDtY1VJQnfGejNcxPx2iEwlSgEeTHC7M5jyuSIdYdaf0IbJ9LlDSxA/vcO/NbGOzEdPKevuiRgcU7Bj+J7tlOrvw6WC4R1RK4JQNowuxoDOwNlAvPD5O5DMiIwku+xbjcxyIwU1yPWIjCgpOmAAHMgBeYI+4+N9Ggk="
  bucket: adv-r.had.co.nz
  region: us-west-2
  local-dir: _site
  skip_cleanup: true
